input "type:keyboard" {
  xkb_layout "latam,us"
  xkb_options "grp:win_space_toggle"
}

input "type:touchpad" {
  tap enabled
}

gaps inner 0
gaps outer 0

default_border none
default_floating_border none
hide_edge_borders both

