set -g default-command "${SHELL}"

set -g mouse on
set -g history-limit 50000

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g default-terminal "screen-256color"
set -g status-style bg=default,fg=white
set -g status-left-length 40
set -g status-left "#[fg=green]Session: #S "
set -g status-right "#[fg=cyan]%Y-%m-%d %H:%M"
